title: Home Assistant
views:
  - path: default_view
    title: Home
    icon: mdi:home
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            entities:
              - entity: sensor.local_ip
                name: 'IP адрес '
              - entity: sensor.system_monitor_last_boot
                name: 'Загрузка (системы) '
          - type: horizontal-stack
            cards:
              - type: tile
                entity: sensor.system_monitor_processor_use
                vertical: true
                name: 'CPU '
                color: lime
              - type: tile
                entity: sensor.system_monitor_processor_temperature
                vertical: true
                name: 'tCPU '
                color: teal
              - type: tile
                entity: sensor.system_monitor_memory_use
                name: 'RAM '
                vertical: true
                color: green
              - type: tile
                entity: sensor.system_monitor_disk_use_percent
                name: 'Disk '
                vertical: true
                color: light-green
          - type: entities
            entities:
              - entity: sensor.system_monitor_swap_use
                name: 'Подкачка '
              - entity: sensor.system_monitor_disk_free
                name: 'Свободно на диске '
              - type: divider
              - entity: sensor.mariadb
                name: 'База данных (размер) '
                icon: mdi:database-eye
              - type: call-service
                icon: mdi:database-minus
                name: 'База данных '
                action_name: Сжать
                service: recorder.purge
                service_data:
                  keep_days: 2
                  repack: true
            show_header_toggle: false
          - type: entities
            entities:
              - entity: sensor.current_version
                name: 'Установлен Home Assistant '
                icon: mdi:home-assistant
              - entity: update.home_assistant_core_update
                icon: mdi:package-up
                name: 'Обновление Home Assistant '
              - type: divider
              - entity: update.hacs_update
                icon: hacs:hacs
                name: 'Обновление HACS '
            show_header_toggle: false
      - type: vertical-stack
        cards:
          - square: false
            type: grid
            cards:
              - type: tile
                entity: switch.rasteniia_kukhnia
                show_entity_picture: true
                vertical: true
                icon: mdi:desk-lamp
                state_content:
                  - state
                  - last-changed
                tap_action:
                  action: more-info
                icon_tap_action:
                  action: toggle
                name: 'Растения 1 '
              - type: tile
                entity: switch.rasteniia
                show_entity_picture: true
                icon: mdi:desk-lamp
                hide_state: false
                state_content:
                  - state
                  - last-changed
                tap_action:
                  action: more-info
                icon_tap_action:
                  action: toggle
                name: 'Растения 2 '
                vertical: true
            columns: 2
          - type: horizontal-stack
            cards:
              - type: conditional
                conditions:
                  - condition: state
                    entity: switch.rasteniia_kukhnia
                    state: 'on'
                card:
                  type: tile
                  entity: sensor.rasteniia_kukhnia_signal_level
                  vertical: true
                  color: light-blue
                  hide_state: false
                  name: 'Сигнал WiFi '
              - type: conditional
                conditions:
                  - condition: state
                    entity: switch.rasteniia
                    state: 'on'
                card:
                  type: tile
                  entity: sensor.rasteniia_signal_level
                  color: light-blue
                  vertical: true
                  name: 'Сигнал WiFi '
          - type: horizontal-stack
            cards:
              - type: tile
                entity: switch.t100_p100_demid
                show_entity_picture: true
                icon: mdi:desktop-classic
                state_content:
                  - state
                  - last-changed
                tap_action:
                  action: toggle
                icon_tap_action:
                  action: more-info
                name: 'Демид ПК '
                vertical: false
              - type: conditional
                conditions:
                  - condition: state
                    entity: switch.t100_p100_demid
                    state: 'on'
                card:
                  type: tile
                  entity: sensor.t100_p100_demid_signal_level
                  vertical: false
                  color: light-blue
                  hide_state: false
                  name: 'Сигнал WiFi '
          - features:
              - type: light-brightness
            type: tile
            entity: light.tpl_l510_torcher
            show_entity_picture: true
            state_content:
              - state
              - brightness
              - last-changed
            tap_action:
              action: toggle
            icon_tap_action:
              action: more-info
            vertical: false
            icon: mdi:floor-lamp-torchiere
            name: 'Торшер '
  - title: Прогноз погоды
    path: unknown
    icon: mdi:sun-thermometer
    badges: []
    cards:
      - show_current: true
        show_forecast: true
        type: weather-forecast
        entity: weather.forecast_home_assistant
        forecast_type: hourly
        name: 'Прогноз погоды '
  - title: Camera
    path: camera
    icon: mdi:video
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - show_state: false
            show_name: false
            camera_view: live
            type: picture-entity
            entity: camera.hikvision_ds_i400_c_mainstream
            image: https://demo.home-assistant.io/stub_config/bedroom.png
            camera_image: camera.hikvision_ds_i400_c_mainstream
          - type: horizontal-stack
            cards:
              - type: gauge
                entity: sensor.hikvision_ds_i400_c_processor_usage
                name: CPU
                severity:
                  green: 0
                  yellow: 60
                  red: 85
                needle: false
                unit: '%'
              - type: glance
                entities:
                  - entity: button.hikvision_ds_i400_c_reboot
                  - entity: binary_sensor.hikvision_ds_i400_c_storage_failure
