homeassistant:
  # Name of the location where Home Assistant is running
  name: Chalet
  # Координаты нашего дома, используются для отрисовки на карте компонента map
  latitude: !secret my_latitude
  longitude: !secret my_longitude
  # Высота над уровнем моря, где используется, можно оставить такой
  elevation: 0
  # Задаем метрическую или имперскую систему исчисления (metric for Metric, imperial for Imperial)
  unit_system: metric
  # Часовой пояс для корректного отображения времени, берем тут: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret my_timezone
  country: !secret my_country
  currency: !secret my_currency
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - !secret localhost
        - !secret local_networks
        - !secret tenet_network
        #- !secret skyfallvpn_network
        #- !secret zerotier_networks
      #trusted_users:
        #192.168.1.80: !secret ha_user_id #Nest Hub Display
      #allow_bypass_login: true
  packages: !include_dir_merge_named includes/packages

# eWeLink (Sonoff)
#sonoff:
#  username: !secret ewelink_login
#  password: !secret ewelink_pswd
  
#hikvison:
#  username: !secret hikvision_login
#  password: !secret hikvision_pswd

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

#sensor: !include_dir_merge_list includes/sensors

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
# Загрузка платформы climate (generic_thermostat) 
climate: !include includes/climate.yaml
# Загрузка платформы camera
#uptime: !include includes/online.yaml
camera: !include includes/camera.yaml
# Загрузка платформы recorder
recorder: !include includes/recorder.yaml
#sensors: !include includes/system_sensors.yaml

# Кнопка 'Система' в левом меню
panel_custom:
  - name: server_state
    sidebar_title: 'Система'
    sidebar_icon: mdi:server
    js_url: /api/hassio/app/entrypoint.js
    url_path: 'hassio/system'
    embed_iframe: true
    require_admin: true
    config:
      ingress: core_configurator
