alias: tuyazb_integration_on
description: ""
triggers:
  - trigger: state
    entity_id:
      - switch.tuyazb_0xa4c1388df3fdf480
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 1
conditions: []
actions:
  - type: turn_on
    device_id: 5d47d833dd229c8fe3dece69f9b4c3d2
    entity_id: bc30b7c0e11c61a5510fa565c932d664
    domain: switch
mode: single
